### ISSUE TITLE
Error -4049

### ISSUE THREAD

**Issue by aninh4t0m4z** [talalmajali/react-native-countdown-component#115]

**Comment by aninh4t0m4z** [comment]
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, lstat 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component'
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\jest-haste-map\build\watchers\NodeWatcher.js:141:12)
    at Walker.emit (node:events:513:28)
    at C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\walker\lib\walker.js:52:12
    at FSReqCallback.oncomplete (node:fs:206:21) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'lstat',
  path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-countdown-component'
}

**Comment by aninh4t0m4z** [comment]
The Debug file. Some help?
0 verbose cli C:\Program Files\nodejs\node.exe C:\Users\ana.tomaz\AppData\Roaming\npm\node_modules\npm\bin\npm-cli.js
1 info using npm@8.19.2
2 info using node@v16.17.0
3 timing npm:load:whichnode Completed in 0ms
4 timing config:load:defaults Completed in 2ms
5 timing config:load:file:C:\Users\ana.tomaz\AppData\Roaming\npm\node_modules\npm\npmrc Completed in 2ms
6 timing config:load:builtin Completed in 3ms
7 timing config:load:cli Completed in 2ms
8 timing config:load:env Completed in 0ms
9 timing config:load:file:C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\.npmrc Completed in 1ms
10 timing config:load:project Completed in 2ms
11 timing config:load:file:C:\Users\ana.tomaz\.npmrc Completed in 0ms
12 timing config:load:user Completed in 0ms
13 timing config:load:file:C:\Users\ana.tomaz\AppData\Roaming\npm\etc\npmrc Completed in 1ms
14 timing config:load:global Completed in 1ms
15 timing config:load:validate Completed in 0ms
16 timing config:load:credentials Completed in 1ms
17 timing config:load:setEnvs Completed in 1ms
18 timing config:load Completed in 13ms
19 timing npm:load:configload Completed in 13ms
20 timing npm:load:mkdirpcache Completed in 1ms
21 timing npm:load:mkdirplogs Completed in 0ms
22 verbose title npm i react-native-countdown-component
23 verbose argv "i" "react-native-countdown-component" "--save" "--force"
24 timing npm:load:setTitle Completed in 2ms
25 timing config:load:flatten Completed in 3ms
26 timing npm:load:display Completed in 5ms
27 verbose logfile logs-max:10 dir:C:\Users\ana.tomaz\AppData\Local\npm-cache\_logs
28 verbose logfile C:\Users\ana.tomaz\AppData\Local\npm-cache\_logs\2022-10-31T15_46_14_024Z-debug-0.log
29 timing npm:load:logFile Completed in 8ms
30 timing npm:load:timers Completed in 0ms
31 timing npm:load:configScope Completed in 0ms
32 warn using --force Recommended protections disabled.
33 timing npm:load Completed in 31ms
34 timing arborist:ctor Completed in 0ms
35 silly logfile start cleaning logs, removing 2 files
36 silly logfile done cleaning log files
37 timing idealTree:init Completed in 1214ms
38 timing idealTree:userRequests Completed in 9ms
39 silly idealTree buildDeps
40 silly fetch manifest react-native-countdown-component@^2.7.1
41 verbose shrinkwrap failed to load node_modules/.package-lock.json [Error: UNKNOWN: unknown error, readlink 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component'] {
41 verbose shrinkwrap   errno: -4094,
41 verbose shrinkwrap   code: 'UNKNOWN',
41 verbose shrinkwrap   syscall: 'readlink',
41 verbose shrinkwrap   path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-countdown-component'
41 verbose shrinkwrap }
42 http fetch GET 200 https://registry.npmjs.org/react-native-countdown-component 1045ms (cache hit)
43 silly placeDep ROOT react-native-countdown-component@2.7.1 REPLACE for: teste01@1.0.0 want: ^2.7.1
44 timing idealTree:#root Completed in 1059ms
45 silly fetch manifest react-native-reanimated@>=2.2.0
46 http fetch GET 200 https://registry.npmjs.org/react-native-reanimated 505ms (cache hit)
47 silly fetch manifest @babel/core@^7.0.0-0
48 http fetch GET 200 https://registry.npmjs.org/@babel%2fcore 31ms (cache hit)
49 silly fetch manifest react@*
50 http fetch GET 200 https://registry.npmjs.org/react 39ms (cache hit)
51 silly fetch manifest react-native@*
52 http fetch GET 200 https://registry.npmjs.org/react-native 43ms (cache hit)
53 silly fetch manifest react@18.1.0
54 warn ERESOLVE overriding peer dependency {
54 warn ERESOLVE   code: 'ERESOLVE',
54 warn ERESOLVE   edge: {
54 warn ERESOLVE     type: 'peer',
54 warn ERESOLVE     name: 'react-native-reanimated',
54 warn ERESOLVE     spec: '>=2.2.0',
54 warn ERESOLVE     error: 'INVALID',
54 warn ERESOLVE     from: {
54 warn ERESOLVE       name: '@gorhom/bottom-sheet',
54 warn ERESOLVE       version: '4.4.5',
54 warn ERESOLVE       location: 'node_modules/@gorhom/bottom-sheet',
54 warn ERESOLVE       isWorkspace: false,
54 warn ERESOLVE       dependents: [Array]
54 warn ERESOLVE     }
54 warn ERESOLVE   },
54 warn ERESOLVE   dep: {
54 warn ERESOLVE     name: 'react-native-reanimated',
54 warn ERESOLVE     version: '2.12.0',
54 warn ERESOLVE     whileInstalling: {
54 warn ERESOLVE       name: '@gorhom/bottom-sheet',
54 warn ERESOLVE       version: '4.4.5',
54 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\@gorhom\\bottom-sheet'
54 warn ERESOLVE     },
54 warn ERESOLVE     location: 'node_modules/react-native-reanimated',
54 warn ERESOLVE     isWorkspace: false,
54 warn ERESOLVE     dependents: [ [Object] ]
54 warn ERESOLVE   },
54 warn ERESOLVE   current: {
54 warn ERESOLVE     name: 'react-native-reanimated',
54 warn ERESOLVE     version: '3.0.0-rc.3',
54 warn ERESOLVE     location: 'node_modules/react-native-reanimated',
54 warn ERESOLVE     isWorkspace: false,
54 warn ERESOLVE     dependents: [ [Object], [Object] ]
54 warn ERESOLVE   },
54 warn ERESOLVE   peerConflict: {
54 warn ERESOLVE     current: {
54 warn ERESOLVE       name: 'react-native-reanimated',
54 warn ERESOLVE       version: '3.0.0-rc.3',
54 warn ERESOLVE       location: 'node_modules/react-native-reanimated',
54 warn ERESOLVE       isWorkspace: false,
54 warn ERESOLVE       dependents: [Array]
54 warn ERESOLVE     },
54 warn ERESOLVE     peer: {
54 warn ERESOLVE       name: 'react-native-reanimated',
54 warn ERESOLVE       version: '2.12.0',
54 warn ERESOLVE       whileInstalling: [Object],
54 warn ERESOLVE       location: 'node_modules/react-native-reanimated',
54 warn ERESOLVE       isWorkspace: false,
54 warn ERESOLVE       dependents: [Array]
54 warn ERESOLVE     }
54 warn ERESOLVE   },
54 warn ERESOLVE   strictPeerDeps: false,
54 warn ERESOLVE   force: true,
54 warn ERESOLVE   isMine: true
54 warn ERESOLVE }
55 timing idealTree:node_modules/@gorhom/bottom-sheet Completed in 694ms
56 silly fetch manifest react-native-reanimated@>=1.7.0
57 warn ERESOLVE overriding peer dependency {
57 warn ERESOLVE   code: 'ERESOLVE',
57 warn ERESOLVE   edge: {
57 warn ERESOLVE     type: 'peer',
57 warn ERESOLVE     name: 'react-native-reanimated',
57 warn ERESOLVE     spec: '>=1.7.0',
57 warn ERESOLVE     error: 'INVALID',
57 warn ERESOLVE     from: {
57 warn ERESOLVE       name: 'progress-react-native',
57 warn ERESOLVE       version: '1.1.0',
57 warn ERESOLVE       location: 'node_modules/progress-react-native',
57 warn ERESOLVE       isWorkspace: false,
57 warn ERESOLVE       dependents: [Array]
57 warn ERESOLVE     }
57 warn ERESOLVE   },
57 warn ERESOLVE   dep: {
57 warn ERESOLVE     name: 'react-native-reanimated',
57 warn ERESOLVE     version: '2.12.0',
57 warn ERESOLVE     whileInstalling: {
57 warn ERESOLVE       name: 'progress-react-native',
57 warn ERESOLVE       version: '1.1.0',
57 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\progress-react-native'
57 warn ERESOLVE     },
57 warn ERESOLVE     location: 'node_modules/react-native-reanimated',
57 warn ERESOLVE     isWorkspace: false,
57 warn ERESOLVE     dependents: [ [Object] ]
57 warn ERESOLVE   },
57 warn ERESOLVE   current: {
57 warn ERESOLVE     name: 'react-native-reanimated',
57 warn ERESOLVE     version: '3.0.0-rc.3',
57 warn ERESOLVE     location: 'node_modules/react-native-reanimated',
57 warn ERESOLVE     isWorkspace: false,
57 warn ERESOLVE     dependents: [ [Object], [Object] ]
57 warn ERESOLVE   },
57 warn ERESOLVE   peerConflict: {
57 warn ERESOLVE     current: {
57 warn ERESOLVE       name: 'react-native-reanimated',
57 warn ERESOLVE       version: '3.0.0-rc.3',
57 warn ERESOLVE       location: 'node_modules/react-native-reanimated',
57 warn ERESOLVE       isWorkspace: false,
57 warn ERESOLVE       dependents: [Array]
57 warn ERESOLVE     },
57 warn ERESOLVE     peer: {
57 warn ERESOLVE       name: 'react-native-reanimated',
57 warn ERESOLVE       version: '2.12.0',
57 warn ERESOLVE       whileInstalling: [Object],
57 warn ERESOLVE       location: 'node_modules/react-native-reanimated',
57 warn ERESOLVE       isWorkspace: false,
57 warn ERESOLVE       dependents: [Array]
57 warn ERESOLVE     }
57 warn ERESOLVE   },
57 warn ERESOLVE   strictPeerDeps: false,
57 warn ERESOLVE   force: true,
57 warn ERESOLVE   isMine: true
57 warn ERESOLVE }
58 timing idealTree:node_modules/progress-react-native Completed in 24ms
59 silly fetch manifest react@^16.0.0
60 warn ERESOLVE overriding peer dependency {
60 warn ERESOLVE   code: 'ERESOLVE',
60 warn ERESOLVE   edge: {
60 warn ERESOLVE     type: 'peer',
60 warn ERESOLVE     name: 'react',
60 warn ERESOLVE     spec: '^16.0.0',
60 warn ERESOLVE     error: 'INVALID',
60 warn ERESOLVE     from: {
60 warn ERESOLVE       name: 'react-dom',
60 warn ERESOLVE       version: '16.8.3',
60 warn ERESOLVE       location: 'node_modules/react-dom',
60 warn ERESOLVE       isWorkspace: false,
60 warn ERESOLVE       dependents: [Array]
60 warn ERESOLVE     }
60 warn ERESOLVE   },
60 warn ERESOLVE   dep: {
60 warn ERESOLVE     name: 'react',
60 warn ERESOLVE     version: '16.14.0',
60 warn ERESOLVE     whileInstalling: {
60 warn ERESOLVE       name: 'react-dom',
60 warn ERESOLVE       version: '16.8.3',
60 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-dom'
60 warn ERESOLVE     },
60 warn ERESOLVE     location: 'node_modules/react',
60 warn ERESOLVE     isWorkspace: false,
60 warn ERESOLVE     dependents: [ [Object] ]
60 warn ERESOLVE   },
60 warn ERESOLVE   current: {
60 warn ERESOLVE     name: 'react',
60 warn ERESOLVE     version: '18.0.0',
60 warn ERESOLVE     location: 'node_modules/react',
60 warn ERESOLVE     isWorkspace: false,
60 warn ERESOLVE     dependents: [
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object], [Object], [Object], [Object],
60 warn ERESOLVE       [Object]
60 warn ERESOLVE     ]
60 warn ERESOLVE   },
60 warn ERESOLVE   peerConflict: {
60 warn ERESOLVE     current: {
60 warn ERESOLVE       name: 'react',
60 warn ERESOLVE       version: '18.0.0',
60 warn ERESOLVE       location: 'node_modules/react',
60 warn ERESOLVE       isWorkspace: false,
60 warn ERESOLVE       dependents: [Array]
60 warn ERESOLVE     },
60 warn ERESOLVE     peer: {
60 warn ERESOLVE       name: 'react',
60 warn ERESOLVE       version: '16.14.0',
60 warn ERESOLVE       whileInstalling: [Object],
60 warn ERESOLVE       location: 'node_modules/react',
60 warn ERESOLVE       isWorkspace: false,
60 warn ERESOLVE       dependents: [Array]
60 warn ERESOLVE     }
60 warn ERESOLVE   },
60 warn ERESOLVE   strictPeerDeps: false,
60 warn ERESOLVE   force: true,
60 warn ERESOLVE   isMine: true
60 warn ERESOLVE }
61 timing idealTree:node_modules/react-dom Completed in 65ms
62 timing idealTree:node_modules/react-native-countdown-component Completed in 0ms
63 silly fetch manifest react-native-safe-area-context@^3.1.9
64 http fetch GET 200 https://registry.npmjs.org/react-native-safe-area-context 272ms (cache miss)
65 warn ERESOLVE overriding peer dependency {
65 warn ERESOLVE   code: 'ERESOLVE',
65 warn ERESOLVE   edge: {
65 warn ERESOLVE     type: 'peer',
65 warn ERESOLVE     name: 'react-native-safe-area-context',
65 warn ERESOLVE     spec: '^3.1.9',
65 warn ERESOLVE     error: 'INVALID',
65 warn ERESOLVE     from: {
65 warn ERESOLVE       name: 'react-native-elements',
65 warn ERESOLVE       version: '3.4.2',
65 warn ERESOLVE       location: 'node_modules/react-native-elements',
65 warn ERESOLVE       isWorkspace: false,
65 warn ERESOLVE       dependents: [Array]
65 warn ERESOLVE     }
65 warn ERESOLVE   },
65 warn ERESOLVE   dep: {
65 warn ERESOLVE     name: 'react-native-safe-area-context',
65 warn ERESOLVE     version: '3.4.1',
65 warn ERESOLVE     whileInstalling: {
65 warn ERESOLVE       name: 'react-native-elements',
65 warn ERESOLVE       version: '3.4.2',
65 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-elements'
65 warn ERESOLVE     },
65 warn ERESOLVE     location: 'node_modules/react-native-safe-area-context',
65 warn ERESOLVE     isWorkspace: false,
65 warn ERESOLVE     dependents: [ [Object] ]
65 warn ERESOLVE   },
65 warn ERESOLVE   current: {
65 warn ERESOLVE     name: 'react-native-safe-area-context',
65 warn ERESOLVE     version: '4.4.1',
65 warn ERESOLVE     location: 'node_modules/react-native-safe-area-context',
65 warn ERESOLVE     isWorkspace: false,
65 warn ERESOLVE     dependents: [ [Object], [Object], [Object], [Object], [Object] ]
65 warn ERESOLVE   },
65 warn ERESOLVE   peerConflict: {
65 warn ERESOLVE     current: {
65 warn ERESOLVE       name: 'react-native-safe-area-context',
65 warn ERESOLVE       version: '4.4.1',
65 warn ERESOLVE       location: 'node_modules/react-native-safe-area-context',
65 warn ERESOLVE       isWorkspace: false,
65 warn ERESOLVE       dependents: [Array]
65 warn ERESOLVE     },
65 warn ERESOLVE     peer: {
65 warn ERESOLVE       name: 'react-native-safe-area-context',
65 warn ERESOLVE       version: '3.4.1',
65 warn ERESOLVE       whileInstalling: [Object],
65 warn ERESOLVE       location: 'node_modules/react-native-safe-area-context',
65 warn ERESOLVE       isWorkspace: false,
65 warn ERESOLVE       dependents: [Array]
65 warn ERESOLVE     }
65 warn ERESOLVE   },
65 warn ERESOLVE   strictPeerDeps: false,
65 warn ERESOLVE   force: true,
65 warn ERESOLVE   isMine: true
65 warn ERESOLVE }
66 timing idealTree:node_modules/react-native-elements Completed in 296ms
67 silly fetch manifest expo@^35.0.0
68 http fetch GET 200 https://registry.npmjs.org/expo 122ms (cache miss)
69 silly fetch manifest react@16.8.3
70 warn ERESOLVE overriding peer dependency {
70 warn ERESOLVE   code: 'ERESOLVE',
70 warn ERESOLVE   edge: {
70 warn ERESOLVE     type: 'peer',
70 warn ERESOLVE     name: 'expo',
70 warn ERESOLVE     spec: '^35.0.0',
70 warn ERESOLVE     error: 'INVALID',
70 warn ERESOLVE     from: {
70 warn ERESOLVE       name: 'react-native-expo-auth',
70 warn ERESOLVE       version: '1.0.1',
70 warn ERESOLVE       location: 'node_modules/react-native-expo-auth',
70 warn ERESOLVE       isWorkspace: false,
70 warn ERESOLVE       dependents: [Array]
70 warn ERESOLVE     }
70 warn ERESOLVE   },
70 warn ERESOLVE   dep: {
70 warn ERESOLVE     name: 'expo',
70 warn ERESOLVE     version: '35.0.1',
70 warn ERESOLVE     whileInstalling: {
70 warn ERESOLVE       name: 'react-native-expo-auth',
70 warn ERESOLVE       version: '1.0.1',
70 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-expo-auth'
70 warn ERESOLVE     },
70 warn ERESOLVE     location: 'node_modules/expo',
70 warn ERESOLVE     isWorkspace: false,
70 warn ERESOLVE     dependents: [ [Object] ]
70 warn ERESOLVE   },
70 warn ERESOLVE   current: {
70 warn ERESOLVE     name: 'expo',
70 warn ERESOLVE     version: '46.0.14',
70 warn ERESOLVE     location: 'node_modules/expo',
70 warn ERESOLVE     isWorkspace: false,
70 warn ERESOLVE     dependents: [
70 warn ERESOLVE       [Object], [Object],
70 warn ERESOLVE       [Object], [Object],
70 warn ERESOLVE       [Object], [Object],
70 warn ERESOLVE       [Object], [Object]
70 warn ERESOLVE     ]
70 warn ERESOLVE   },
70 warn ERESOLVE   peerConflict: {
70 warn ERESOLVE     current: {
70 warn ERESOLVE       name: 'expo',
70 warn ERESOLVE       version: '46.0.14',
70 warn ERESOLVE       location: 'node_modules/expo',
70 warn ERESOLVE       isWorkspace: false,
70 warn ERESOLVE       dependents: [Array]
70 warn ERESOLVE     },
70 warn ERESOLVE     peer: {
70 warn ERESOLVE       name: 'expo',
70 warn ERESOLVE       version: '35.0.1',
70 warn ERESOLVE       whileInstalling: [Object],
70 warn ERESOLVE       location: 'node_modules/expo',
70 warn ERESOLVE       isWorkspace: false,
70 warn ERESOLVE       dependents: [Array]
70 warn ERESOLVE     }
70 warn ERESOLVE   },
70 warn ERESOLVE   strictPeerDeps: false,
70 warn ERESOLVE   force: true,
70 warn ERESOLVE   isMine: true
70 warn ERESOLVE }
71 warn ERESOLVE overriding peer dependency {
71 warn ERESOLVE   code: 'ERESOLVE',
71 warn ERESOLVE   edge: {
71 warn ERESOLVE     type: 'peer',
71 warn ERESOLVE     name: 'react',
71 warn ERESOLVE     spec: '16.8.3',
71 warn ERESOLVE     error: 'INVALID',
71 warn ERESOLVE     from: {
71 warn ERESOLVE       name: 'react-native-expo-auth',
71 warn ERESOLVE       version: '1.0.1',
71 warn ERESOLVE       location: 'node_modules/react-native-expo-auth',
71 warn ERESOLVE       isWorkspace: false,
71 warn ERESOLVE       dependents: [Array]
71 warn ERESOLVE     }
71 warn ERESOLVE   },
71 warn ERESOLVE   dep: {
71 warn ERESOLVE     name: 'react',
71 warn ERESOLVE     version: '16.8.3',
71 warn ERESOLVE     whileInstalling: {
71 warn ERESOLVE       name: 'react-native-expo-auth',
71 warn ERESOLVE       version: '1.0.1',
71 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-expo-auth'
71 warn ERESOLVE     },
71 warn ERESOLVE     location: 'node_modules/react',
71 warn ERESOLVE     isWorkspace: false,
71 warn ERESOLVE     dependents: [ [Object] ]
71 warn ERESOLVE   },
71 warn ERESOLVE   current: {
71 warn ERESOLVE     name: 'react',
71 warn ERESOLVE     version: '18.0.0',
71 warn ERESOLVE     location: 'node_modules/react',
71 warn ERESOLVE     isWorkspace: false,
71 warn ERESOLVE     dependents: [
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object], [Object], [Object], [Object],
71 warn ERESOLVE       [Object]
71 warn ERESOLVE     ]
71 warn ERESOLVE   },
71 warn ERESOLVE   peerConflict: {
71 warn ERESOLVE     current: {
71 warn ERESOLVE       name: 'react',
71 warn ERESOLVE       version: '18.0.0',
71 warn ERESOLVE       location: 'node_modules/react',
71 warn ERESOLVE       isWorkspace: false,
71 warn ERESOLVE       dependents: [Array]
71 warn ERESOLVE     },
71 warn ERESOLVE     peer: {
71 warn ERESOLVE       name: 'react',
71 warn ERESOLVE       version: '16.8.3',
71 warn ERESOLVE       whileInstalling: [Object],
71 warn ERESOLVE       location: 'node_modules/react',
71 warn ERESOLVE       isWorkspace: false,
71 warn ERESOLVE       dependents: [Array]
71 warn ERESOLVE     }
71 warn ERESOLVE   },
71 warn ERESOLVE   strictPeerDeps: false,
71 warn ERESOLVE   force: true,
71 warn ERESOLVE   isMine: true
71 warn ERESOLVE }
72 timing idealTree:node_modules/react-native-expo-auth Completed in 170ms
73 silly fetch manifest react-native-modalize@1.2.0
74 http fetch GET 200 https://registry.npmjs.org/react-native-modalize 896ms (cache miss)
75 silly fetch manifest react-native-gesture-handler@> 1.0.0
76 http fetch GET 200 https://registry.npmjs.org/react-native-gesture-handler 88ms (cache miss)
77 warn ERESOLVE overriding peer dependency {
77 warn ERESOLVE   code: 'ERESOLVE',
77 warn ERESOLVE   edge: {
77 warn ERESOLVE     type: 'peer',
77 warn ERESOLVE     name: 'react-native-modalize',
77 warn ERESOLVE     spec: '1.2.0',
77 warn ERESOLVE     error: 'INVALID',
77 warn ERESOLVE     from: {
77 warn ERESOLVE       name: 'react-native-modalize-webview',
77 warn ERESOLVE       version: '1.0.0',
77 warn ERESOLVE       location: 'node_modules/react-native-modalize-webview',
77 warn ERESOLVE       isWorkspace: false,
77 warn ERESOLVE       dependents: [Array]
77 warn ERESOLVE     }
77 warn ERESOLVE   },
77 warn ERESOLVE   dep: {
77 warn ERESOLVE     name: 'react-native-modalize',
77 warn ERESOLVE     version: '1.2.0',
77 warn ERESOLVE     whileInstalling: {
77 warn ERESOLVE       name: 'react-native-modalize-webview',
77 warn ERESOLVE       version: '1.0.0',
77 warn ERESOLVE       path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-modalize-webview'
77 warn ERESOLVE     },
77 warn ERESOLVE     location: 'node_modules/react-native-modalize',
77 warn ERESOLVE     isWorkspace: false,
77 warn ERESOLVE     dependents: [ [Object] ]
77 warn ERESOLVE   },
77 warn ERESOLVE   current: {
77 warn ERESOLVE     name: 'react-native-modalize',
77 warn ERESOLVE     version: '2.1.1',
77 warn ERESOLVE     location: 'node_modules/react-native-modalize',
77 warn ERESOLVE     isWorkspace: false,
77 warn ERESOLVE     dependents: [ [Object] ]
77 warn ERESOLVE   },
77 warn ERESOLVE   peerConflict: {
77 warn ERESOLVE     current: {
77 warn ERESOLVE       name: 'react-native-modalize',
77 warn ERESOLVE       version: '2.1.1',
77 warn ERESOLVE       location: 'node_modules/react-native-modalize',
77 warn ERESOLVE       isWorkspace: false,
77 warn ERESOLVE       dependents: [Array]
77 warn ERESOLVE     },
77 warn ERESOLVE     peer: {
77 warn ERESOLVE       name: 'react-native-modalize',
77 warn ERESOLVE       version: '1.2.0',
77 warn ERESOLVE       whileInstalling: [Object],
77 warn ERESOLVE       location: 'node_modules/react-native-modalize',
77 warn ERESOLVE       isWorkspace: false,
77 warn ERESOLVE       dependents: [Array]
77 warn ERESOLVE     }
77 warn ERESOLVE   },
77 warn ERESOLVE   strictPeerDeps: false,
77 warn ERESOLVE   force: true,
77 warn ERESOLVE   isMine: true
77 warn ERESOLVE }
78 timing idealTree:node_modules/react-native-modalize-webview Completed in 1001ms
79 timing idealTree:buildDeps Completed in 3312ms
80 timing idealTree:fixDepFlags Completed in 18ms
81 timing idealTree Completed in 4558ms
82 timing reify:loadTrees Completed in 4559ms
83 timing reify:diffTrees Completed in 214ms
84 silly reify mark retired [
84 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-countdown-component'
84 silly reify ]
85 silly reify mark retired [
85 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\@babel\\helper-member-expression-to-functions'
85 silly reify ]
86 silly reify mark retired [
86 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\snapdragon\\node_modules\\source-map'
86 silly reify ]
87 silly reify moves {
87 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-countdown-component': 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\.react-native-countdown-component-1GLcm0Xb',
87 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\@babel\\helper-member-expression-to-functions': 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\@babel\\.helper-member-expression-to-functions-OPyeFDkd',
87 silly reify   'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\snapdragon\\node_modules\\source-map': 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\snapdragon\\node_modules\\.source-map-rRFdPhWg'
87 silly reify }
88 timing reify:rollback:retireShallow Completed in 3ms
89 timing command:i Completed in 4794ms
90 verbose stack Error: UNKNOWN: unknown error, rename 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component' -> 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\.react-native-countdown-component-1GLcm0Xb'
91 verbose cwd C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01
92 verbose Windows_NT 10.0.22000
93 verbose node v16.17.0
94 verbose npm  v8.19.2
95 error code UNKNOWN
96 error syscall rename
97 error path C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component
98 error dest C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\.react-native-countdown-component-1GLcm0Xb
99 error errno -4094
100 error UNKNOWN: unknown error, rename 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component' -> 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\.react-native-countdown-component-1GLcm0Xb'
101 verbose exit -4094
102 timing npm Completed in 5017ms
103 verbose unfinished npm timer reify 1667231174242
104 verbose unfinished npm timer reify:retireShallow 1667231179027
105 verbose code -4094
106 error A complete log of this run can be found in:
106 error     C:\Users\ana.tomaz\AppData\Local\npm-cache\_logs\2022-10-31T15_46_14_024Z-debug-0.log

**Comment by aninh4t0m4z** [comment]
Logs for your project will appear below. Press Ctrl+C to exit.
node:events:491
      throw er; // Unhandled 'error' event
      ^

Error: UNKNOWN: unknown error, lstat 'C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\react-native-countdown-component'
Emitted 'error' event on NodeWatcher instance at:
    at NodeWatcher.checkedEmitError (C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\jest-haste-map\build\watchers\NodeWatcher.js:141:12)
    at Walker.emit (node:events:513:28)
    at C:\Users\ana.tomaz\OneDrive - Online Applications\Área de Trabalho\teste01\node_modules\walker\lib\walker.js:52:12
    at FSReqCallback.oncomplete (node:fs:206:21) {
  errno: -4094,
  code: 'UNKNOWN',
  syscall: 'lstat',
  path: 'C:\\Users\\ana.tomaz\\OneDrive - Online Applications\\Área de Trabalho\\teste01\\node_modules\\react-native-countdown-component'
}
